create table public.users (
	user_id INT,
	email VARCHAR(50),
	first_name VARCHAR(50),
	h_address VARCHAR(50),
	h_city VARCHAR(50),
	h_state VARCHAR(50),
	h_zip VARCHAR(50),
	is_accepting_rides VARCHAR(50),
	is_active VARCHAR(50),
	is_driver VARCHAR(50),
	last_name VARCHAR(50),
	phone_number VARCHAR(50),
	user_name VARCHAR(50),
	w_address VARCHAR(50),
	w_city VARCHAR(50),
	w_state VARCHAR(50),
	w_zip VARCHAR(50),
	batch_number INT
);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (1, 'dbernth0@rakuten.co.jp', 'Dorris', '06494 Transport Hill', 'Norwalk', 'CT', '06859', true, false, false, 'Bernth', '203-836-2020', 'dbernth0', '92 Lyons Drive', 'Springfield', 'MA', '01105', 5);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (2, 'bcaudelier1@t-online.de', 'Becki', '42 Eastwood Avenue', 'Winston Salem', 'NC', '27116', true, true, true, 'Caudelier', '336-794-5276', 'bcaudelier1', '13426 Comanche Junction', 'Boston', 'MA', '02283', 18);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (3, 'rmackett2@ehow.com', 'Rory', '7 Garrison Drive', 'Lynchburg', 'VA', '24515', false, true, true, 'Mackett', '434-559-8367', 'rmackett2', '4 Graedel Way', 'Shawnee Mission', 'KS', '66276', 1);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (4, 'apechell3@dropbox.com', 'Adrian', '67033 Glacier Hill Court', 'Jamaica', 'NY', '11407', true, true, false, 'Pechell', '516-543-2072', 'apechell3', '3182 Memorial Junction', 'Boston', 'MA', '02119', 13);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (5, 'mkeirl4@ocn.ne.jp', 'Maggi', '2 Manufacturers Street', 'Dallas', 'TX', '75310', true, false, true, 'Keirl', '214-535-9807', 'mkeirl4', '39 Almo Street', 'White Plains', 'NY', '10606', 17);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (6, 'cfleeming5@a8.net', 'Corina', '95 School Parkway', 'Paterson', 'NJ', '07544', true, false, false, 'Fleeming', '862-442-9371', 'cfleeming5', '69 Anzinger Hill', 'Houston', 'TX', '77234', 20);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (7, 'oraggett6@posterous.com', 'Opalina', '31 Spaight Court', 'Boston', 'MA', '02163', true, true, false, 'Raggett', '781-569-0881', 'oraggett6', '310 Eggendart Junction', 'Tucson', 'AZ', '85720', 13);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (8, 'clindsell7@google.de', 'Cordula', '9635 5th Pass', 'Phoenix', 'AZ', '85020', true, true, false, 'Lindsell', '480-672-5955', 'clindsell7', '74853 Twin Pines Place', 'Lancaster', 'CA', '93584', 6);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (9, 'ldemiranda8@t-online.de', 'Lorinda', '8 Melvin Court', 'Norfolk', 'VA', '23551', false, true, true, 'De Miranda', '757-465-7256', 'ldemiranda8', '46238 Bunker Hill Court', 'Tulsa', 'OK', '74133', 16);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (10, 'ktorritti9@engadget.com', 'Keefer', '15 Hansons Drive', 'Scranton', 'PA', '18514', true, true, true, 'Torritti', '570-815-8645', 'ktorritti9', '62311 Killdeer Point', 'Rochester', 'MN', '55905', 5);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (11, 'nmcilveena@virginia.edu', 'Nehemiah', '410 Longview Crossing', 'Erie', 'PA', '16505', true, true, true, 'McIlveen', '814-236-4189', 'nmcilveena', '759 Burning Wood Avenue', 'Abilene', 'TX', '79605', 17);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (12, 'wleninb@ycombinator.com', 'Wendeline', '649 Red Cloud Street', 'Saint Petersburg', 'FL', '33737', false, true, true, 'Lenin', '727-540-2394', 'wleninb', '22 Oxford Drive', 'Anchorage', 'AK', '99512', 10);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (13, 'fwigmorec@e-recht24.de', 'Filmore', '661 Morrow Center', 'Houston', 'TX', '77045', true, true, true, 'Wigmore', '713-600-4814', 'fwigmorec', '0414 Sugar Center', 'Buffalo', 'NY', '14215', 10);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (14, 'opochond@google.cn', 'Oswell', '194 Old Gate Place', 'Stamford', 'CT', '06912', true, false, true, 'Pochon', '203-836-2047', 'opochond', '65538 Clove Pass', 'Battle Creek', 'MI', '49018', 6);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (15, 'fworthingtone@sfgate.com', 'Flora', '4094 Starling Road', 'Sioux Falls', 'SD', '57110', true, false, true, 'Worthington', '605-454-1374', 'fworthingtone', '251 Fisk Junction', 'Macon', 'GA', '31296', 16);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (16, 'ehucklebyf@fc2.com', 'Edmon', '78 Grayhawk Center', 'Portland', 'OR', '97271', true, true, true, 'Huckleby', '971-946-3558', 'ehucklebyf', '15728 Ridgeway Pass', 'Young America', 'MN', '55573', 6);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (17, 'akennaghg@nbcnews.com', 'Aldus', '8 Corscot Lane', 'Santa Monica', 'CA', '90410', true, true, false, 'Kennagh', '310-343-1226', 'akennaghg', '52 Beilfuss Terrace', 'Portland', 'OR', '97201', 11);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (18, 'eshallooh@vk.com', 'Edgar', '62 Roxbury Avenue', 'Charlotte', 'NC', '28247', false, true, false, 'Shalloo', '704-604-4698', 'eshallooh', '5427 Hallows Hill', 'Young America', 'MN', '55564', 9);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (19, 'pniemieci@springer.com', 'Padgett', '289 Bonner Plaza', 'Nashville', 'TN', '37215', false, false, true, 'Niemiec', '615-786-0730', 'pniemieci', '27657 Dwight Trail', 'Los Angeles', 'CA', '90087', 11);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (20, 'dfalconertaylorj@army.mil', 'Darcee', '48 Anthes Trail', 'Kalamazoo', 'MI', '49048', false, true, false, 'Falconer-Taylor', '269-327-9286', 'dfalconertaylorj', '7222 Summit Place', 'Arlington', 'VA', '22225', 2);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (21, 'eraubenheimerk@wp.com', 'Eden', '7852 Eagle Crest Court', 'Augusta', 'GA', '30911', false, false, true, 'Raubenheimer', '706-451-1847', 'eraubenheimerk', '083 Melody Junction', 'Sacramento', 'CA', '95894', 14);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (22, 'fhayterl@cornell.edu', 'Fedora', '5 Upham Pass', 'Topeka', 'KS', '66622', true, true, false, 'Hayter', '785-691-0970', 'fhayterl', '76469 Anthes Park', 'Indianapolis', 'IN', '46278', 11);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (23, 'bliptrodm@china.com.cn', 'Brett', '4455 Green Drive', 'Columbus', 'GA', '31914', false, false, false, 'Liptrod', '706-847-2309', 'bliptrodm', '71 Parkside Terrace', 'Huntington', 'WV', '25726', 16);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (24, 'mskermern@hp.com', 'Marne', '2 Hermina Way', 'El Paso', 'TX', '79989', true, false, false, 'Skermer', '915-152-3304', 'mskermern', '5 8th Plaza', 'Nashville', 'TN', '37245', 1);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (25, 'nfurmongero@slate.com', 'Norby', '91 Westport Center', 'Chicago', 'IL', '60609', false, false, false, 'Furmonger', '312-167-5880', 'nfurmongero', '2023 Golf View Parkway', 'El Paso', 'TX', '79911', 15);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (26, 'llintallp@cargocollective.com', 'Lemar', '32385 Vahlen Circle', 'Des Moines', 'IA', '50981', true, false, true, 'Lintall', '515-437-2785', 'llintallp', '18 Londonderry Plaza', 'Philadelphia', 'PA', '19196', 6);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (27, 'lmarchingtonq@cnbc.com', 'Lois', '46466 Macpherson Avenue', 'South Lake Tahoe', 'CA', '96154', false, true, true, 'Marchington', '530-800-6328', 'lmarchingtonq', '710 Lindbergh Place', 'Dallas', 'TX', '75397', 2);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (28, 'abarhemsr@si.edu', 'Aggy', '3522 Graedel Plaza', 'Seattle', 'WA', '98109', true, true, true, 'Barhems', '425-546-2069', 'abarhemsr', '80336 Sloan Drive', 'Miami', 'FL', '33185', 13);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (29, 'tcordinglys@nbcnews.com', 'Trace', '4 Straubel Street', 'Tulsa', 'OK', '74141', true, true, false, 'Cordingly', '918-739-5671', 'tcordinglys', '5050 Moland Circle', 'Las Vegas', 'NV', '89193', 13);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (30, 'elanghornet@artisteer.com', 'Emelina', '52 Bultman Pass', 'Little Rock', 'AR', '72204', false, false, false, 'Langhorne', '501-712-9919', 'elanghornet', '6 7th Lane', 'Simi Valley', 'CA', '93094', 14);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (31, 'jmacdonnellu@nsw.gov.au', 'Jillene', '4342 1st Avenue', 'Denver', 'CO', '80241', false, true, false, 'MacDonnell', '303-302-9405', 'jmacdonnellu', '115 Becker Drive', 'Virginia Beach', 'VA', '23459', 10);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (32, 'dnealyv@deviantart.com', 'Dniren', '263 Rutledge Plaza', 'Seattle', 'WA', '98175', true, false, false, 'Nealy', '206-481-2059', 'dnealyv', '66 Westerfield Parkway', 'Albany', 'NY', '12222', 2);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (33, 'schiezew@ocn.ne.jp', 'Shandie', '48 Waywood Crossing', 'Springfield', 'IL', '62794', false, true, true, 'Chieze', '217-581-4783', 'schiezew', '1 Glacier Hill Avenue', 'Sacramento', 'CA', '94230', 14);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (34, 'bwadesworthx@yale.edu', 'Becky', '6300 Homewood Court', 'Ann Arbor', 'MI', '48107', false, true, false, 'Wadesworth', '734-950-5662', 'bwadesworthx', '5418 Bonner Junction', 'Charlotte', 'NC', '28220', 15);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (35, 'dslowgravey@economist.com', 'Dillon', '29953 Kipling Hill', 'Camden', 'NJ', '08104', false, true, false, 'Slowgrave', '856-973-7827', 'dslowgravey', '08 Chive Drive', 'South Bend', 'IN', '46614', 19);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (36, 'drobusz@netvibes.com', 'Daffi', '5414 Londonderry Point', 'Wichita', 'KS', '67230', false, false, true, 'Robus', '316-871-2167', 'drobusz', '5100 Darwin Crossing', 'Hartford', 'CT', '06152', 19);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (37, 'bbode10@squidoo.com', 'Beulah', '1 Calypso Road', 'Columbus', 'GA', '31904', true, false, true, 'Bode', '706-787-8093', 'bbode10', '12266 Clyde Gallagher Point', 'Laredo', 'TX', '78044', 19);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (38, 'vmeyrick11@mysql.com', 'Vikky', '1 Ludington Lane', 'Schaumburg', 'IL', '60193', false, true, true, 'Meyrick', '224-680-3199', 'vmeyrick11', '00129 Little Fleur Parkway', 'Milwaukee', 'WI', '53225', 18);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (39, 'ymusso12@marriott.com', 'Yorker', '13 Dwight Way', 'Jersey City', 'NJ', '07305', false, true, false, 'Musso', '201-862-9780', 'ymusso12', '2500 Susan Drive', 'Kansas City', 'MO', '64130', 8);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (40, 'etite13@lycos.com', 'Edouard', '11561 Golf View Junction', 'Houston', 'TX', '77206', true, true, true, 'Tite', '713-198-1515', 'etite13', '0817 Blue Bill Park Lane', 'Washington', 'DC', '20299', 7);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (41, 'gnewnham14@oakley.com', 'Gaby', '366 Jay Parkway', 'Waco', 'TX', '76796', false, true, false, 'Newnham', '254-813-6540', 'gnewnham14', '8422 Prairieview Hill', 'Charlotte', 'NC', '28235', 10);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (42, 'celsby15@hc360.com', 'Carmela', '1 Kipling Point', 'Charlotte', 'NC', '28215', false, false, false, 'Elsby', '704-297-3653', 'celsby15', '281 Tomscot Alley', 'Kansas City', 'MO', '64199', 19);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (43, 'nrubinsohn16@businessinsider.com', 'Ninnette', '20 Knutson Drive', 'Plano', 'TX', '75074', false, true, true, 'Rubinsohn', '469-436-5238', 'nrubinsohn16', '4 Mockingbird Junction', 'Asheville', 'NC', '28815', 16);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (44, 'measbie17@ucoz.ru', 'Meggy', '36 Springview Circle', 'Oakland', 'CA', '94611', false, false, false, 'Easbie', '415-498-3905', 'measbie17', '83840 La Follette Alley', 'Philadelphia', 'PA', '19109', 17);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (45, 'mgillicuddy18@kickstarter.com', 'Margarethe', '2314 Westport Crossing', 'Grand Rapids', 'MI', '49505', true, false, true, 'Gillicuddy', '616-234-7299', 'mgillicuddy18', '721 Independence Alley', 'Punta Gorda', 'FL', '33982', 7);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (46, 'ckensy19@wisc.edu', 'Cairistiona', '33 Cordelia Parkway', 'Dayton', 'OH', '45432', false, true, false, 'Kensy', '937-190-0015', 'ckensy19', '11 High Crossing Court', 'Saint Augustine', 'FL', '32092', 4);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (47, 'jbessell1a@umich.edu', 'Jules', '467 Banding Avenue', 'Kansas City', 'MO', '64187', false, false, false, 'Bessell', '816-707-1731', 'jbessell1a', '12 Texas Center', 'Gatesville', 'TX', '76598', 16);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (48, 'mamori1b@cargocollective.com', 'Martguerita', '36 Lien Hill', 'Atlanta', 'GA', '30343', true, true, true, 'Amori', '404-571-9192', 'mamori1b', '0 Service Junction', 'Topeka', 'KS', '66629', 15);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (49, 'mgrigs1c@bluehost.com', 'Mora', '8311 Jana Junction', 'Atlanta', 'GA', '30358', false, true, false, 'Grigs', '404-353-6545', 'mgrigs1c', '9829 Corscot Lane', 'Bronx', 'NY', '10464', 17);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (50, 'hhalsted1d@state.gov', 'Huntington', '75971 Clemons Plaza', 'Colorado Springs', 'CO', '80915', false, false, false, 'Halsted', '719-865-9464', 'hhalsted1d', '6 Loomis Plaza', 'Washington', 'DC', '56944', 5);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (51, 'lida1e@smh.com.au', 'Lyssa', '97 Hollow Ridge Terrace', 'Cleveland', 'OH', '44118', true, true, true, 'Ida', '216-937-0237', 'lida1e', '45 Badeau Terrace', 'Bridgeport', 'CT', '06606', 4);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (52, 'amcneely1f@free.fr', 'Amelina', '65574 Burrows Center', 'Anchorage', 'AK', '99522', true, true, true, 'McNeely', '907-516-4323', 'amcneely1f', '9 Lillian Place', 'Orlando', 'FL', '32835', 15);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (53, 'kmatantsev1g@adobe.com', 'Kristina', '0 Columbus Junction', 'Dayton', 'OH', '45470', true, true, false, 'Matantsev', '937-727-8196', 'kmatantsev1g', '334 Boyd Park', 'Washington', 'DC', '20430', 6);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (54, 'shawkswood1h@netscape.com', 'Stormie', '4728 Veith Point', 'Grand Rapids', 'MI', '49510', true, false, true, 'Hawkswood', '616-597-4354', 'shawkswood1h', '9 Florence Alley', 'Springfield', 'MA', '01105', 20);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (55, 'kkitchinham1i@furl.net', 'Kirsteni', '99 Merchant Court', 'Rochester', 'NY', '14614', true, false, false, 'Kitchinham', '315-518-9512', 'kkitchinham1i', '74411 Arapahoe Street', 'Louisville', 'KY', '40293', 1);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (56, 'nwhaymand1j@rediff.com', 'Norton', '4 Shelley Center', 'Washington', 'DC', '20210', true, false, true, 'Whaymand', '202-136-6414', 'nwhaymand1j', '65 Lawn Place', 'York', 'PA', '17405', 20);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (57, 'ialliott1k@edublogs.org', 'Iseabal', '9 Carberry Hill', 'Montgomery', 'AL', '36177', false, true, true, 'Alliott', '334-242-3066', 'ialliott1k', '53 Everett Place', 'Scottsdale', 'AZ', '85255', 4);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (58, 'aembery1l@lycos.com', 'Austine', '0 Spaight Way', 'Lafayette', 'LA', '70505', false, false, true, 'Embery', '337-511-1972', 'aembery1l', '6666 David Center', 'Kansas City', 'MO', '64160', 5);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (59, 'bcorradi1m@aol.com', 'Bev', '8 Kropf Way', 'Minneapolis', 'MN', '55407', false, true, true, 'Corradi', '952-767-7658', 'bcorradi1m', '5050 Hanover Pass', 'Pompano Beach', 'FL', '33069', 16);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (60, 'csidworth1n@telegraph.co.uk', 'Clea', '5462 Oxford Terrace', 'Los Angeles', 'CA', '90015', false, true, false, 'Sidworth', '626-552-7295', 'csidworth1n', '19127 Sutherland Circle', 'Jacksonville', 'FL', '32209', 20);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (61, 'ohigounet1o@github.com', 'Olympe', '9 Melvin Terrace', 'Monticello', 'MN', '55585', true, false, false, 'Higounet', '763-871-6461', 'ohigounet1o', '14 Knutson Terrace', 'Fort Worth', 'TX', '76105', 1);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (62, 'dmarioneau1p@si.edu', 'Derrick', '8 American Ash Street', 'Cheyenne', 'WY', '82007', false, false, true, 'Marioneau', '307-436-8494', 'dmarioneau1p', '24 Prairie Rose Alley', 'Buffalo', 'NY', '14205', 18);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (63, 'tbloxsome1q@istockphoto.com', 'Tatiana', '07 Monterey Court', 'Brooklyn', 'NY', '11247', false, false, false, 'Bloxsome', '212-521-9984', 'tbloxsome1q', '8 Eastwood Hill', 'Washington', 'DC', '20599', 6);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (64, 'nsokill1r@barnesandnoble.com', 'Newton', '5 Gulseth Plaza', 'West Palm Beach', 'FL', '33421', false, true, false, 'Sokill', '561-232-4721', 'nsokill1r', '27212 2nd Way', 'Los Angeles', 'CA', '90087', 1);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (65, 'cnathon1s@eepurl.com', 'Claribel', '2 Burrows Hill', 'Chicago', 'IL', '60630', true, false, false, 'Nathon', '847-338-5779', 'cnathon1s', '5 Bunting Parkway', 'Mountain View', 'CA', '94042', 17);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (66, 'srobert1t@de.vu', 'Shoshanna', '22779 Mayfield Way', 'Philadelphia', 'PA', '19172', true, true, false, 'Robert', '215-592-9810', 'srobert1t', '4 Homewood Center', 'Amarillo', 'TX', '79116', 2);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (67, 'mgamwell1u@bbc.co.uk', 'Marabel', '65886 Hanover Street', 'East Saint Louis', 'IL', '62205', true, false, false, 'Gamwell', '618-369-5600', 'mgamwell1u', '3 Forest Run Avenue', 'Washington', 'DC', '20260', 2);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (68, 'bculpen1v@nhs.uk', 'Beverlie', '76263 Ryan Park', 'Temple', 'TX', '76505', true, false, true, 'Culpen', '254-411-8178', 'bculpen1v', '8909 Anthes Road', 'New York City', 'NY', '10004', 2);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (69, 'rstanning1w@yale.edu', 'Richard', '131 Sunnyside Court', 'Duluth', 'MN', '55805', false, true, true, 'Stanning', '218-829-4645', 'rstanning1w', '95 Sunfield Parkway', 'Palmdale', 'CA', '93591', 13);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (70, 'zantonnikov1x@istockphoto.com', 'Zollie', '81 Algoma Avenue', 'New York City', 'NY', '10184', true, false, true, 'Antonnikov', '212-632-1309', 'zantonnikov1x', '1 Carpenter Junction', 'Newark', 'NJ', '07195', 17);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (71, 'bbelt1y@pcworld.com', 'Bibi', '021 Elgar Junction', 'Charleston', 'WV', '25356', false, true, true, 'Belt', '304-605-2063', 'bbelt1y', '279 Duke Hill', 'Raleigh', 'NC', '27658', 3);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (72, 'bhellens1z@craigslist.org', 'Bertrand', '12588 Pine View Court', 'New York City', 'NY', '10060', true, true, true, 'Hellens', '646-398-1978', 'bhellens1z', '15 Walton Way', 'San Antonio', 'TX', '78205', 18);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (73, 'dbortoloni20@dion.ne.jp', 'Delia', '124 Fuller Street', 'Knoxville', 'TN', '37919', true, true, true, 'Bortoloni', '865-542-4722', 'dbortoloni20', '4 Sommers Park', 'North Hollywood', 'CA', '91606', 17);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (74, 'ocalderbank21@springer.com', 'Odille', '06413 American Ash Alley', 'Houston', 'TX', '77095', false, true, false, 'Calderbank', '713-151-7287', 'ocalderbank21', '9 Crownhardt Drive', 'Sacramento', 'CA', '95818', 18);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (75, 'llorraway22@homestead.com', 'Luke', '1 Prairie Rose Parkway', 'Austin', 'TX', '78789', true, false, false, 'Lorraway', '512-866-2699', 'llorraway22', '63 Lyons Park', 'Dallas', 'TX', '75310', 20);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (76, 'pgranger23@drupal.org', 'Pauly', '912 Raven Lane', 'Philadelphia', 'PA', '19125', false, true, false, 'Granger', '215-443-1578', 'pgranger23', '6 Mallory Court', 'Washington', 'DC', '20591', 4);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (77, 'rpuxley24@amazon.co.uk', 'Rosina', '175 Tennyson Pass', 'Washington', 'DC', '20557', true, true, false, 'Puxley', '202-297-6380', 'rpuxley24', '7 Dayton Avenue', 'Lansing', 'MI', '48919', 3);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (78, 'aecob25@php.net', 'Amelia', '88 Nova Alley', 'Oklahoma City', 'OK', '73197', true, false, true, 'Ecob', '405-359-3711', 'aecob25', '9 Shasta Point', 'New Orleans', 'LA', '70154', 1);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (79, 'nvanyushin26@samsung.com', 'Niccolo', '3157 Fairfield Plaza', 'South Bend', 'IN', '46699', true, true, true, 'Vanyushin', '574-575-2956', 'nvanyushin26', '96254 Grasskamp Way', 'Wilmington', 'DE', '19892', 6);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (80, 'mwalkling27@multiply.com', 'Mendie', '86 Debra Crossing', 'Pittsburgh', 'PA', '15261', false, true, true, 'Walkling', '412-966-4612', 'mwalkling27', '21702 Oak Trail', 'Jacksonville', 'FL', '32255', 10);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (81, 'zkirkebye28@wp.com', 'Zilvia', '63026 Rieder Plaza', 'Alhambra', 'CA', '91841', false, false, false, 'Kirkebye', '626-960-5135', 'zkirkebye28', '4707 Grim Point', 'Orlando', 'FL', '32830', 12);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (82, 'mthiem29@bing.com', 'Mireielle', '33857 8th Court', 'Boulder', 'CO', '80328', false, false, true, 'Thiem', '303-732-5996', 'mthiem29', '3 Granby Pass', 'San Antonio', 'TX', '78285', 11);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (83, 'nnias2a@google.es', 'Nettle', '41061 Cascade Park', 'Mobile', 'AL', '36616', false, true, true, 'Nias', '251-528-2079', 'nnias2a', '192 Bowman Plaza', 'El Paso', 'TX', '79955', 6);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (84, 'ndevereux2b@geocities.com', 'Nicolais', '74360 International Lane', 'San Diego', 'CA', '92121', false, false, false, 'Devereux', '858-660-2403', 'ndevereux2b', '71 Hagan Terrace', 'Boston', 'MA', '02298', 11);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (85, 'rmettetal2c@wix.com', 'Rufus', '1 Hanover Way', 'Greensboro', 'NC', '27415', true, false, true, 'Mettetal', '336-495-5149', 'rmettetal2c', '82000 Tennessee Lane', 'Baltimore', 'MD', '21265', 2);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (86, 'granby2d@nih.gov', 'Golda', '96947 Upham Road', 'Minneapolis', 'MN', '55480', false, true, false, 'Ranby', '612-428-6509', 'granby2d', '6 Fisk Alley', 'Ogden', 'UT', '84409', 7);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (87, 'dsandercock2e@diigo.com', 'Donielle', '4 Ridge Oak Plaza', 'El Paso', 'TX', '79968', false, true, true, 'Sandercock', '915-148-7285', 'dsandercock2e', '5 Monterey Park', 'Indianapolis', 'IN', '46226', 17);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (88, 'lkiehnlt2f@jimdo.com', 'Linell', '6 Dexter Lane', 'El Paso', 'TX', '79955', true, true, false, 'Kiehnlt', '915-867-2779', 'lkiehnlt2f', '756 Northview Park', 'Denver', 'CO', '80235', 20);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (89, 'mcosely2g@imdb.com', 'Modesty', '3475 Orin Crossing', 'Oklahoma City', 'OK', '73104', false, true, false, 'Cosely', '405-840-5105', 'mcosely2g', '30479 Gale Street', 'Baltimore', 'MD', '21239', 15);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (90, 'tredwall2h@cnn.com', 'Tamar', '994 Union Junction', 'Albany', 'NY', '12247', true, true, true, 'Redwall', '518-862-0040', 'tredwall2h', '3 Mandrake Avenue', 'Oklahoma City', 'OK', '73104', 14);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (91, 'jwalthew2i@state.gov', 'Jacob', '65494 Surrey Trail', 'Zephyrhills', 'FL', '33543', false, true, true, 'Walthew', '813-611-3355', 'jwalthew2i', '974 Sherman Circle', 'Fort Smith', 'AR', '72916', 9);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (92, 'lrudman2j@bigcartel.com', 'Lonnie', '7 Northwestern Point', 'Fort Worth', 'TX', '76129', true, false, false, 'Rudman', '817-496-3698', 'lrudman2j', '3464 Ludington Junction', 'Visalia', 'CA', '93291', 9);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (93, 'nmcelane2k@goodreads.com', 'Norton', '8 Cambridge Plaza', 'Albuquerque', 'NM', '87121', true, true, true, 'McElane', '505-691-3132', 'nmcelane2k', '147 Forest Dale Court', 'Boulder', 'CO', '80328', 15);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (94, 'mbausmann2l@wiley.com', 'Maury', '008 Gina Hill', 'Portland', 'OR', '97221', true, true, false, 'Bausmann', '503-772-7716', 'mbausmann2l', '00 Hovde Drive', 'Corpus Christi', 'TX', '78426', 19);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (95, 'gstanbury2m@smh.com.au', 'Ginger', '0 Birchwood Drive', 'Wichita', 'KS', '67230', true, true, false, 'Stanbury', '316-226-4996', 'gstanbury2m', '60 Mariners Cove Road', 'Columbia', 'SC', '29215', 4);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (96, 'wdyerson2n@comcast.net', 'Westley', '3603 Dawn Hill', 'Erie', 'PA', '16550', true, true, true, 'Dyerson', '814-119-0637', 'wdyerson2n', '0 Canary Hill', 'Minneapolis', 'MN', '55458', 7);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (97, 'hdimitrov2o@thetimes.co.uk', 'Humfried', '897 Artisan Plaza', 'Fresno', 'CA', '93778', true, true, false, 'Dimitrov', '559-779-1304', 'hdimitrov2o', '0 Mcbride Trail', 'Stamford', 'CT', '06922', 20);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (98, 'ifitchet2p@yahoo.com', 'Ingamar', '38 West Terrace', 'Lakeland', 'FL', '33811', true, true, true, 'Fitchet', '863-916-5823', 'ifitchet2p', '917 Schurz Parkway', 'Little Rock', 'AR', '72204', 20);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (99, 'ledden2q@discuz.net', 'Lonni', '75 Eastlawn Terrace', 'Greensboro', 'NC', '27415', false, true, false, 'Edden', '336-198-6127', 'ledden2q', '0 Express Parkway', 'Orlando', 'FL', '32819', 7);
insert into public.users (user_id, email, first_name, h_address, h_city, h_state, h_zip, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, w_address, w_city, w_state, w_zip, batch_number) values (100, 'htitman2r@arizona.edu', 'Hunfredo', '87709 Petterle Lane', 'Charleston', 'WV', '25331', true, false, true, 'Titman', '304-241-4949', 'htitman2r', '76882 Acker Road', 'Dallas', 'TX', '75358', 8);
